repos:
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
    - id: pycodestyle
      name: pycodestyle
      entry: pycodestyle
      types: [ python ]
      language: system
      args:
        - --max-line-length=120
