repos:
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
    - id: pylint
      name: pylint
      entry: pylint
      types: [ python ]
      language: system
      exclude: ^src/test/
      args:
        - --max-line-length=120

